# Generated by Django 2.1.2 on 2019-03-20 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(max_length=60)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('startingweight', models.SmallIntegerField()),
                ('targetweight', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.SmallIntegerField()),
                ('birthdate', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='goals',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Profile'),
        ),
    ]
